### PR TITLE
fix(update-form): add styling changes to update form

### PR DESCRIPTION
**Pull request by PatrickDohn**
#### Summary

- Work Type:  Fix 
- Fixes: 

#### What I did

- Added styling to update form
- fixed width issues
- 

#### Notes / Research / References

- 
-

#### Screenshots

Screen Shot 2021-02-16 at 9 42 54 PM

#### Checklist

- [x] Commits are descriptive
- [x] Has Summary

### CODE REVIEW

**Comment by davidholyko** [comment]
image

Are the styling changes based on this spec?

**Comment by PatrickDohn** [comment]
> image
> 
> Are the styling changes based on this spec?

Yes

**Comment by davidholyko** [comment]
the screenshot and changes don't seem to reflect the design requirements. Can you get it closer? Or should this be iteration 1 and do you expect a follow up iteration to complete the design implementation

**Comment by robrichardsdpt** [comment]
LGTM

**Review by robrichardsdpt — APPROVED** [review]
LGTM

**Pull request merged**
